### ISSUE TITLE
Error while unpacking

### ISSUE THREAD

**Issue by jigypatel** [Ramonymous/ThePAK#1]
Bro the one from youtube i am getting error while unpacking 
It gives error
1) Unpack                                       
2) Repack
3) Quit                                         Please enter your choice: 1                     1) MagicBullet.pak                              2) Quit                                         Please select a file to unpack: 1
You picked MagicBullet.pak which is file 1     
Error while loading /data/data/com.termux/files/usr/share/quickbms/quickbms: No such file or directory

**Comment by Ramonymous** [comment]
Please do the install process first by running "bash setup"

**Comment by Ramonymous** [comment]
For videos on the YouTube channel, I only teach how to use it, for the installation process it is in the description of this repository. Before you do what you watch on youtube, first time you have to do the installation.
